In [ ]:
diccionario_pokemon={'1 era Evo' : {'charmarnder', 'squirtle', 'bulbasur'}, '2 era Evo': {'Charmeleon', 'Wartortle', 'ivysaur'}}

In [ ]:
diccionario_pokemon['1 era Evo']

{'bulbasur', 'charmarnder', 'squirtle'}

In [ ]:
diccionario_pokemon.values()

dict_values([{'squirtle', 'bulbasur', 'charmarnder'}, {'Charmeleon', 'Wartortle', 'ivysaur'}])

In [ ]:
diccionario_pokemon['2 era Evo']

{'Charmeleon', 'Wartortle', 'ivysaur'}

In [ ]:
diccionario_banco={'Usuario':{'Enrique', 'Carlos', 'Laura'}, 'No.Cuenta': {'Enrique': '00001', 'Carlos': '00002', 'Laura': '00003'}}

In [ ]:
diccionario_banco['No.Cuenta']['Enrique']

'00001'

In [ ]:
for Usuario in diccionario_banco['Usuario']:
    print(Usuario, 'tiene la cuenta', diccionario_banco['No.Cuenta'][Usuario])

Carlos tiene la cuenta 00002
Laura tiene la cuenta 00003
Enrique tiene la cuenta 00001


In [ ]:
diccionario_pokemon['1 era Evo']=['charmarnder', 'squirtle', 'bulbasur', 'pikachu']

In [ ]:
diccionario_pokemon

{'1 era Evo': ['charmarnder', 'squirtle', 'bulbasur', 'pikachu'],
 '2 era Evo': {'Charmeleon', 'Wartortle', 'ivysaur'}}

In [ ]:
Lista_frutas={'rojas': 'manzana', 'amarillas': 'pera', 'moradas':'uva'}
comodin = Lista_frutas.copy()
Lista_frutas.pop('rojas')
Lista_frutas

{'amarillas': 'pera', 'moradas': 'uva'}

In [ ]:
Lista_frutas

{'amarillas': 'pera', 'moradas': 'uva'}

In [ ]:
comodin

{'rojas': 'manzana', 'amarillas': 'pera', 'moradas': 'uva'}

In [ ]:
id(comodin)

134313348754496

In [ ]:
id(Lista_frutas)

134313349895424

In [ ]:
tupla1=(1,2,3,4,5,6,7,8,9)

In [ ]:
type(tupla1)

tuple

In [ ]:
tupla1[0]

1

In [ ]:
tupla2=(10,11,12,13,14,15,16,17,18)

In [ ]:
tupla1+tupla2

(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18)

In [ ]:
lista1=[1,2,3]
lista2=[4,5,6]

In [ ]:
lista1+lista2

[1, 2, 3, 4, 5, 6]

In [ ]:
tupla1[0]=True #no se puede cambiar elementos en las tuplas, en general no se pueden hacer modificaciones.

TypeError: 'tuple' object does not support item assignment

In [ ]:
lista1[0]=True

In [ ]:
lista1

[True, 2, 3]

#Estructuras de control

In [ ]:
lista_mascota=[] #lista vacia, se declara una vez afuera del proceso iterativo
while True: #o 1
  x1= input('Dame una mascota y si quieres terminar escribe salir: \t')
  x=x1.lower()
  lista_mascota.append(x)
  if x=='gato':
    print('miau')
  elif x=='perro':
      print('guau')
  elif x== 'loro':
      print('loro')
  elif x== 'tortuga':
      print('tortuga')
  elif x== 'salir':
      break
  else:
      print('mascota no valida')

Dame una mascota y si quieres terminar escribe salir: 	gato
miau
Dame una mascota y si quieres terminar escribe salir: 	perro
guau
Dame una mascota y si quieres terminar escribe salir: 	tortuga
tortuga
Dame una mascota y si quieres terminar escribe salir: 	salir


In [ ]:
x1='GATO'
x2=x1.lower()
print(x2)
x3=x1.upper()
print(x3)
x4=x1.capitalize()
print(x4)

gato
GATO
Gato


In [ ]:
for i in lista_mascota:
  print(i)

gato
perro
tortuga
salir


In [ ]:
for i in range(0,105,5):
  print(i)

0
5
10
15
20
25
30
35
40
45
50
55
60
65
70
75
80
85
90
95
100


In [ ]:
i=0
while i<10:
  i=i+1
  print(i)

1
2
3
4
5
6
7
8
9
10


In [ ]:
print(lista_mascota)

['gato', 'perro', 'tortuga', 'salir']


In [ ]:
#suma de gauss
n=100
suma=n*(n+1)/2 #formula directa de gauss
print(suma)

suma=0
for i in range(1,101):
  suma=suma+i #proceso iterativo
print(suma)

5050.0
5050


In [ ]:
#factorial entero o flotante
n=int(input('Dame un numero entero para calcular el factorial: '))
fac=1.0
for i in range(1,n+1):
  fac=fac*i
print(fac)

#si las operaciones son enteros 1558

Dame un numero entero para calcular el factorial: 200
inf


In [ ]:
def funcion(variable1, var2, var3):
  y=variable1**2+var2**2+var3**2
  print('Esta es la funcion 1')
  return y

In [ ]:
print(funcion(1,1,1))

Esta es la funcion 1
3


In [ ]:
def f(x):
  return x**2

In [ ]:
def g(x):
  return x+1

In [ ]:
print(f(g(1)))

4


In [ ]:
def varios():
  n=int(input('Dime cuantos elementos guardaras en la lista'))
  lista=[]
  for i in range(n):
    x=float(input('Da el elemento %d '%i))
    lista.append(x)
  return lista

In [ ]:
varios()

Dime cuantos elementos guardaras en la lista3
Da el elemento 0 11


[11.0]

In [ ]:
def promedio():
  n=int(input('Dime cuantos elementos guardaras en la lista'))
  lista=[]
  suma=0
  for i in range(n):
    x=float(input('Da el elemento %d '%i))
    suma=suma+x
    lista.append(x)
  return lista,suma/n

In [ ]:
promedio()

Dime cuantos elementos guardaras en la lista3
Da el elemento 0 4
Da el elemento 1 1
Da el elemento 2 23


([4.0, 1.0, 23.0], 9.333333333333334)

In [ ]:
def funprointer():
  n=int(input('Dime cuantos elementos tiene el vector 1'))
  m=int(input('Dime cuantos elementos tiene el vector 2'))
  lista1=[]
  lista2=[]
  suma=0
  for i in range(n):
    x=float(input('Da el elemento %d '%i))
    y=float(input('Da el elemento %d '%i))
    suma=suma+x*y
    lista1.append(x)
    lista2.append(y)
  return lista1, lista2, suma

In [ ]:
funprointer()

Dime cuantos elementos tiene el vector12
Dime cuantos elementos tiene el vector22
Da el elemento 0 1
Da el elemento 0 1
Da el elemento 1 2
Da el elemento 1 2


([1.0, 2.0], [1.0, 2.0], 5.0)

In [ ]:
import numpy

In [ ]:
import numpy as np

In [ ]:
from numpy import sin

In [ ]:
pip install numpy

In [ ]:
lista=[1,2,3,4]
v= np.array(lista)

In [ ]:
type(v)

numpy.ndarray

In [ ]:
a=[1,2,3,4]
b=[5,6,7,8]
v1=np.array(a)
v2=np.array(b)

In [ ]:
a+b

[1, 2, 3, 4, 5, 6, 7, 8]

In [ ]:
v1+v2

array([ 6,  8, 10, 12])

In [ ]:
a*3

[1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4]

In [ ]:
v1*3

array([ 3,  6,  9, 12])

In [ ]:
lista_de_listas=[[1,2,3],[4,5,6], [7,8,9]]

In [ ]:
lista_de_listas

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [ ]:
matriz=np.array(lista_de_listas)

In [ ]:
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
identidad= np.array([[1,0,0],[0,1,0],[0,0,1]])

In [ ]:
def prod_matrices(M1,M2):

array([[1, 0, 0],
       [0, 5, 0],
       [0, 0, 9]])