#Numpy

In [ ]:
import numpy as np

In [ ]:
lista_de_listas=[[1,2,3],[4,5,6], [7,8,9]]

In [ ]:
lista_de_listas

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [ ]:
matriz=np.array(lista_de_listas)

In [ ]:
print(matriz)
matriz[0][1]

[[1 2 3]
 [4 5 6]
 [7 8 9]]


2

In [ ]:
matriz.shape[0]

3

In [ ]:
def traza_matriz(M):
  n=M.shape[0]
  traza=0
  for i in range(n):
    traza+= M[i][i]
  return traza

In [ ]:
traza_matriz(M = matriz)

15

In [ ]:
def determinante_2x2(M):
  n=M.shape[0]
  a=M[0][0]
  b=M[0][1]
  c=M[1][0]
  d=M[1][1]
  return  a*d-c*b

In [ ]:
M_2=np.array([[1,2],[3,4]])

In [ ]:
determinante_2x2(M_2)

-2

In [ ]:
M= np.arange(1,13).reshape(3,4)

In [ ]:
def ProductoCruz_3x3():
  n=int(input('Dime cuantos elementos tiene el vector 1'))
  m=int(input('Dime cuantos elementos tiene el vector 2'))
  lista1=[]
  lista2=[]
  a=lista1[0][0]
  b=lista1[0][1]
  c=lista1[0][2]
  d=lista2[1][0]
  e=lista2[1][1]
  f=lista2[1][2]
  return  lista1, lista2, (b*f-c*e), -(af-cd), (ae-bd)



SyntaxError: incomplete input (<ipython-input-43-5744b341e728>, line 7)